https-ssl2

diff --git a/0x10-https_ssl/0-world_wide_web b/0x10-https_ssl/0-world_wide_web
--- a/0x10-https_ssl/0-world_wide_web
+++ b/0x10-https_ssl/0-world_wide_web
@@ -1,18 +1,31 @@
 #!/usr/bin/env bash
-# write a Bash script that will display information about the subdomains
 
-dns_config () {
-    script=$(dig "$2"."$1" | grep -A1 'ANSWER SECTION:' | tr '\t' '\n' | tail -2 | tr '\n' ' ')
-    echo "$2 $script" | awk '{print "The subdomain " $1 " is a " $2 " record and points to " $3}'
+dns_config() {
+    local domain=$1
+    local subdomain=$2
+
+    dig_output=$(dig "$subdomain.$domain" +short)
+
+    if [ -z "$dig_output" ]; then
+        echo "Error: Unable to retrieve DNS information for $subdomain.$domain"
+        return
+    fi
+
+    record_type=$(dig "$subdomain.$domain" | awk '/IN/{print $4}')
+    destination=$(echo "$dig_output" | head -n1)
+
+    printf "The subdomain %s is a %s record and points to %s\n" "$subdomain" "$record_type" "$destination"
 }
 
-if [ "$#" == 1 ]
-then
-  dns_config "$1" "www"
-  dns_config "$1" "lb-01"
-  dns_config "$1" "web-01"
-  dns_config "$1" "web-02"
-elif [ "$#" == 2 ]
-then
-  dns_config "$1" "$2"
+if [ "$#" == 1 ]; then
+    dns_config "$1" "www"
+    dns_config "$1" "lb-01"
+    dns_config "$1" "web-01"
+    dns_config "$1" "web-02"
+elif [ "$#" == 2 ]; then
+    dns_config "$1" "$2"
+else
+    echo "Usage: $0 <domain> [subdomain]"
+    exit 1
 fi
+
